name: build-and-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: build-and-test
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Install depends
      run: sudo apt-get -y install bash cmake default-jre-headless lcov libsodium-dev libcmocka-dev

    - name: Build and test
      run: |
        cmake -DSANITIZE_ADDRESS=On -DSANITIZE_UNDEFINED=On -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=On -DBUILD_BENCHMARK=On -DBUILD_EXAMPLES=On -DENABLE_COVERAGE=On .
        make -j$(nproc)
        ctest
        sh test_echo_with_java.sh
        gcov src/CMakeFiles/salt.dir/salt.c.gcno src/CMakeFiles/salt.dir/salti_handshake.c.gcno src/CMakeFiles/salt.dir/salti_util.c.gcno
